services:
  - type: web
    name: odoo-ims
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run seed && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_FILE
        value: ./database/ims.db
